In [2]:
import pandas as pd
df = pd.read_csv("data/simulated/customer_churn_5000.csv")

In [3]:
df.shape

(5000, 20)

In [4]:
df.isnull().sum()

customerid                    0
customer_name                 0
gender                        0
country                       0
state                         0
dob                           0
subscription_start_date       0
subscription_type             0
renewal_date                  0
plan_type                     0
contract_type                 0
cancellation_date          3996
cancellation_reason           0
monthly_charges               0
cltv                          0
churn_score                   0
churn_flag                    0
escalations                   0
csat_score                    0
complaint_count               0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.dtypes

customerid                   int64
customer_name               object
gender                      object
country                     object
state                       object
dob                         object
subscription_start_date     object
subscription_type           object
renewal_date                object
plan_type                   object
contract_type               object
cancellation_date           object
cancellation_reason         object
monthly_charges              int64
cltv                       float64
churn_score                  int64
churn_flag                   int64
escalations                  int64
csat_score                   int64
complaint_count              int64
dtype: object

In [7]:
df.describe()

,customerid,monthly_charges,cltv,churn_score,churn_flag,escalations,csat_score,complaint_count
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,102500.500000,663.946000,26461.966800,41.823400,0.200800,0.625400,3.732800,1.322600
std,1443.520003,319.154088,20097.395262,21.150491,0.400639,0.889063,1.184265,1.314106
min,100001.000000,299.000000,3588.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,101250.750000,410.000000,12830.750000,27.000000,0.000000,0.000000,3.000000,0.000000
50%,102500.500000,559.000000,20168.000000,38.000000,0.000000,0.000000,4.000000,1.000000
75%,103750.250000,841.000000,33019.250000,54.000000,0.000000,1.000000,5.000000,2.000000
max,105000.000000,1498.000000,112866.000000,100.000000,1.000000,3.000000,5.000000,6.000000

In [8]:
df.describe(include="object")

,customer_name,gender,country,state,dob,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason
count,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,1004,5000
unique,4944,2,1,8,4260,4999,2,5000,3,2,1004,6
top,Charvi Dara,Male,India,Maharashtra,1998-09-08,2023-11-27 07:14:36,Regular,2025-02-09 01:37:15,Basic,Monthly,2024-06-21 00:34:28,Active
freq,3,2609,5000,1117,4,2,3988,1,2209,3155,1,3996

In [9]:
df["churn_flag"].value_counts(normalize=True)*100

churn_flag
0    79.92
1    20.08
Name: proportion, dtype: float64

In [10]:
df["plan_type"].value_counts(normalize=True)*100

plan_type
Basic       44.18
Standard    35.58
Premium     20.24
Name: proportion, dtype: float64

In [11]:
df["contract_type"].value_counts(normalize=True)*100

contract_type
Monthly    63.1
Annual     36.9
Name: proportion, dtype: float64

In [12]:
df["csat_score"].value_counts().sort_index()

csat_score
1     327
2     498
3     896
4    1742
5    1537
Name: count, dtype: int64

In [13]:
pd.crosstab(
    df["contract_type"],
    df["churn_flag"],
    normalize="index"
)*100

churn_flag             0          1
contract_type
Annual         87.046070  12.953930
Monthly        75.752773  24.247227

In [14]:
pd.crosstab(
    df["plan_type"],
    df["churn_flag"],
    normalize="index"
)*100

churn_flag          0          1
plan_type
Basic       78.361249  21.638751
Premium     86.067194  13.932806
Standard    78.358628  21.641372